name: Terraform Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Working Directory
      run: |
          echo "Current directory:"
          pwd
          echo "Files in the current directory:"
          ls -l  

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Initialize Terraform
      run: terraform init
      working-directory: networking/Networking_dbs/Networking_dbs/terraform

    - name: Plan Terraform Deployment
      run: terraform plan
      working-directory: networking_dbs/terraform

    - name: Apply Terraform Configuration
      run: terraform apply -auto-approve
      working-directory: networking/Networking_dbs/Networking_dbs/terraform
